### ISSUE TITLE
Assembly Loading in a mixed framework environment

### ISSUE THREAD

**Issue by raffaeler** [dotnet/core-setup#1810]
[This is just a discussion / brainstorming]
Let's say there is a scenario with:
- An App running either with netstandard or netcoreapp
- A common netstandard dll defining an interface
- A number of plugins, either netstandard or netstandard, that are NOT directly referenced by the App

The discussion is about the best solution and/or the missing runtime and tools to ease developer's life.

Here there are my points:

1. When the App declare multiple frameworks there is currently no way from VS2017 to choose the runtime to debug with
<TargetFrameworks>netcoreapp1.1;net462</TargetFrameworks>
2. The AssemblyLoadContext is netcore specific even if it is inside the System.Runtime.Loader nestandard dll. This means I am required to if/endif in C# code to pick the `AssemblyLoadContext.Default.LoadFromAssemblyPath` or `Assembly.LoadFrom` method.
3. When I want to load a plugin, I also need to know if its framework is compatible with the one the App is actually running (either nestandard or netcoreapp).
3a. What is the best way to identify the current running framework?
3b. How can I identify the framework used from a dll? I tried with metadata but I could not find any info (see here [https://github.com/dotnet/corefx/issues/17309](https://github.com/dotnet/corefx/issues/17309).
4. Identifying plugin dependencies. I need to deploy separately the App and the plugins (that can come from 3rd parties). This means that every plugin should be able to be shipped with all the required dependencies (as it already happens when you deploy an app with Self-Contained Deploying SCD). There is no current tooling in VS2017 or in the CLI to copy in a folder the required library dependencies. The deps.json file can be a starting point but a tool is required as the content may vary depending on the runtimes as well.
5. When I manually load the plugin, its dependencies cannot be found automatically from the loader. For example If I reference System.Net.Ping 4.3 nuget package the runtime will look for System.Net.Ping.dll 4.0.1 (or similar). The only way to make the runtime load the plugin is to intercept the AssemblyResolving event (and AssemblyResolve for netstandard).
6. Identifying missing dlls. There is still no fuslogvw tool (or similar) to identify failed bindings.
7. If both the App and the plugin references, for example, System.IO package but in different versions, what is the best practice for managing version differences? The first (App) win? Or what?

[A draft for a netstandard/netcoreapp loader is here](https://gist.github.com/raffaeler/f8cf7c87ff9cd8e48c2b608b95b7cff4)

**Comment by raffaeler** [comment]
Point 3
One way to identify the current running framework (netstandard vs netcoreapp) is the following.
This is fine for code compiled with the latest compilers.
Older assemblies do not have this attribute, therefore this system is not reliable to retrieve the framework they were supposed to run on.

```
private string GetRunningFramework()
{
    var attributeValue = Assembly.GetEntryAssembly().GetCustomAttribute<System.Runtime.Versioning.TargetFrameworkAttribute>();
    return attributeValue.FrameworkName;
}

```

_The nuget package Microsoft.Extensions.Platform.Abstractions (currently version 1.1.0) use this same attribute._

Results:
- netcoreapp: ".NETCoreApp,Version=v1.1"
- net462: ".NETFramework,Version=v4.6.2"
which is the value of the TargetFrameworkAttribute at assembly level (it does read this attribute indeed).

**Comment by raffaeler** [comment]
Point 1. Curiosity about VS2017
As already said, the editor is aware of the "TargetFramework", but the debugger is not.
This is a valid multi-targeting for the new csproj.
`<TargetFrameworks>netcoreapp1.1;net462</TargetFrameworks>`

If instead I specify the following, the *last* wins and the first is just ignored.
```
<TargetFramework>net462</TargetFramework>
<TargetFramework>netcoreapp1.1</TargetFramework>
```
Every time you need to debug under one of the two frameworks, you need to change the cspoj commenting "TargetFrameworks" and uncommenting one of the "TargetFramework".
When these tags are edited, VS2017 will reload the project.

**Comment by Petermarcu** [comment]
@ramarag @gkhanna79

**Comment by gkhanna79** [comment]
> The AssemblyLoadContext is netcore specific

This is on our backlog to enable for Desktop FX as well.

> What is the best way to identify the current running framework

@AlexGhiondea can you chime in on this?

> There is no current tooling in VS2017 or in the CLI to copy in a folder the required library dependencies

@livarcocc should chime in on this.

> If I reference System.Net.Ping 4.3 nuget package the runtime will look for System.Net.Ping.dll 4.0.1 (or similar).

This is by design since nuget packages do not have any 1:1 assembly/assembly version associations with their contents.

 >  The only way to make the runtime load the plugin is to intercept the AssemblyResolving event (and AssemblyResolve for netstandard).

This is the correct way to help resolve dependencies that are not known at app build time.

> Identifying missing dlls. There is still no fuslogvw tool (or similar) to identify failed bindings.

Can you please elaborate on this? If a dependency is declared in app's deps.json but not present in the app, you will get a failure to start the app indicating the missing dependency. Also, to see how the loading works, set COREHOST_TRACE=1 in the environment.

> If both the App and the plugin references, for example, System.IO package but in different versions

This is a perennial versioning policy question and is less of a runtime policy but more of an app policy. There can be various approaches on it:

1)  If app wants to be the owner of resolving the conflict, it needs to ensure that it carries all such _common_ dependencies with it. Thus, when the plugin is loaded in the same context as the application and ends up requesting the assembly, it will get resolved from what the app loaded. Either it will service the request or fail it. 

2) If the app wants the plugin to own all of its dependencies, then the app author should have guidelines for plugin authors like:

- Plugin must carry all of its dependencies
- Plugin will be loaded in its own custom load context. To override assemblies that may get resolved from the app's context, the custom load context's Load method will need to be overridden.
- For any dependencies that are not found in app's context and not part of the plugin, plugin must subscribe to LoadContext's Resolving event to help resolve them.

More details on AssemblyLoadContext are at https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md. 

Hope this helps.

**Comment by raffaeler** [comment]
Thank you @gkhanna79 
About the «Identifying missing dlls.» point.
I knew about COREHOST_TRACE but the logs are not as accurate as the fusion log viewer (fuslogvw.exe) is for the .net framework. 
Are you telling me that will not be replacement for that tool in .net core?

**Comment by gkhanna79** [comment]
What specific things do you find missing that you are looking for? Currently, there is no plan for something like that for .NET Core.

**Comment by raffaeler** [comment]
The fuslogvw trace all the binding resolution steps: the folders where the assembly is looked for, and if it is found traces the version mismatch and the exact reason why the version cannot be loaded.

**Comment by gkhanna79** [comment]
The same semantic equivalent is shown in corehost trace output, corresponding to the simpler binding model of .net core.



Thanks,
Gaurav


-------- Original message --------

**Comment by raffaeler** [comment]
hmm, in the trace I have created right now I just see
`Could not load file or assembly 'System.Net.Ping, Version=4.0.0.0, ....`
but there is no mention about the places where the dll has been looked for.

In a different test, I copied the 4.0.0.0 version of the System.Net.NetworkInformation.dll instead of the version 4.1.1.0 and there was no mention of it in the trace.
I obtained instead this output. It would be very hard to undertstand the error depends on the System.Net.NetworkInformation and not the System.Core.
`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.`

Also, please can you answer to the previous question about the trace variables docs?

**Comment by sherlockkong** [comment]
We also encountered the same problem.

Environment: Azure VM ubuntu16.04 
We use server(netcoreapp2.0) to load some plugins(netstandard2.0),

AssemblyLoadContext.Default.LoadFromAssemblyPath can not load assembly correctly.
The error message like this: 
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Grapecity.Enterprise.Server.Plugins.PluginsImpl.<<LoadPlugins>g__GetAssemblyPlugins1_2>d.MoveNext()

But Assembly.LoadFrom can load the plugins correctly.

Is there other problem? What is the best way to load the plugins?

@raffaeler What your solution now? 
Thank you for your help!

**Comment by raffaeler** [comment]
@sherlockkong you should look the inner exceptions of the typeloadexception. There could be many different reasons. For example any exception inside a static constructor causes a typeloadexception.
In my case the workaround is the code inside the gist I posted previously in this thread.
hth

**Comment by sherlockkong** [comment]
@raffaeler I mean Assembly.LoadFrom works fine on ubuntu16.04, so I replaced AssemblyLoadContext.Default.LoadFromAssemblyPath with Assembly.LoadFrom.

But I do not know if Assembly.LoadFrom works fine in all situations. 
Have you ever encountered a situation where Assembly.LoadFrom does not work properly?

Thanks
