### ISSUE TITLE
runtime.win10*.Microsoft.NETCore.UniversalWindowsPlatform packages are getting built on linux/osx builds

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2014]
## Steps to reproduce
build dotnet/core-setup on a linux or OSX machine.

## Expected  behavior
We should not be producing `runtime.win10` packages, since this isn't building on win10.

## Actual behavior
```
eerhardt@eerhardt-Virtual-Machine:~/git/core-setup/artifacts/ubuntu.14.04-x64/corehost$ ls -al
...
-rwxrw-r-- 1 eerhardt eerhardt   883676 Apr 10 11:21 runtime.ubuntu.14.04-x64.Microsoft.NETCore.DotNetHostPolicy.2.0.0-preview1-001948-                   00.symbols.nupkg
-rwxrw-r-- 1 eerhardt eerhardt   703114 Apr 10 11:21 runtime.ubuntu.14.04-x64.Microsoft.NETCore.DotNetHostResolver.2.0.0-preview1-00194                   8-00.nupkg
-rwxrw-r-- 1 eerhardt eerhardt   703114 Apr 10 11:21 runtime.ubuntu.14.04-x64.Microsoft.NETCore.DotNetHostResolver.2.0.0-preview1-00194                   8-00.symbols.nupkg
-rwxrw-r-- 1 eerhardt eerhardt  7794176 Apr 10 11:23 runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-00                   1948-00.nupkg
-rwxrw-r-- 1 eerhardt eerhardt 16199962 Apr 10 11:23 runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-00                   1948-00.symbols.nupkg
-rwxrw-r-- 1 eerhardt eerhardt 19468525 Apr 10 11:24 runtime.win10-x64.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-001948                   -00.nupkg
-rwxrw-r-- 1 eerhardt eerhardt 60734115 Apr 10 11:24 runtime.win10-x64.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-001948                   -00.symbols.nupkg
```

**Comment by eerhardt** [comment]
From my naive investigation, I believe the problem is:

https://github.com/dotnet/core-setup/blob/master/pkg/projects/Microsoft.NETCore.UniversalWindowsPlatform/uapRIDs.props#L3-L5

```XML
  <PropertyGroup Condition="'$(PackageRID)' == ''">
    <PackageRID>win10-$(Platform)</PackageRID>
  </PropertyGroup>
```

Which hard-codes `win10` even when not building on windows.  Thus, later when we try to [FilterProjects](https://github.com/dotnet/core-setup/blob/master/pkg/projects/dir.traversal.targets#L11), we are picking up the `win10` packages even when building on non-Windows.

**Comment by joperezr** [comment]
those package RIDS are fine, since we actually want the rids to only build on windows builds. This package is for UAP, hence there are no runtime-specific assets for anything other than Windows. The problem here is that we don't have a good way to filter out a package from building, I'll try to figure out a way.

**Comment by eerhardt** [comment]
I believe there already is a good way of filtering out packages from building using the existing `OfficialBuildRID` mechanism.

If you would set `$(PackageRID)` to the RID that is currently being built, instead of hard-coding it, then that FilterProjects target wouldn't pick up any of the `OfficialBuildRID`s.

Then, all you need to do to tell [this piece](https://github.com/dotnet/core-setup/blob/master/pkg/projects/dir.props#L63-L69) not to add the current `$(PackageRID)` in your case.

```XML
  <ItemGroup>
    <!-- Ensure we have a RID-specific package for the current build, even if it isn't in our official set -->
    <BuildRID Include="@(OfficialBuildRID)" Exclude="$(PackageRID)"/>
    <BuildRID Include="$(PackageRID)">
      <Platform>$(Platform)</Platform>
    </BuildRID>
  </ItemGroup>
```

Maybe create a new property called `$(OnlyIncludeOfficialBuildRIDs)` or something similar that tells this code not to build packages when we aren't on an Official Build RID.

/cc @ericstj

**Comment by eerhardt** [comment]
Unless you just want to skip building everything in the `UniversalWindowsPlatform` package when not building on Windows...  which would probably be best.

**Comment by joperezr** [comment]
yup, that is actually what I want, since It's ok if the identity package is not built at all on non-Windows.

**Comment by eerhardt** [comment]
Note that this issue appears to be blocking getting a clean core-setup official build.  We keep getting errors like:

```
2017-04-10T16:21:16.5709850Z Publishing file '/Users/buildagent/agent/_work/5/s/artifacts/osx.10.12-x64/corehost/runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-001950-00.nupkg' to 'master/Binaries/2.0.0-preview1-001950-00/runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-001950-00.nupkg'
2017-04-10T16:21:20.0495810Z Publishing package master/Binaries/2.0.0-preview1-001950-00/runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-001950-00.nupkg to Azure.
2017-04-10T16:21:20.0514430Z Publishing file '/Users/buildagent/agent/_work/5/s/artifacts/osx.10.12-x64/corehost/runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-001950-00.symbols.nupkg' to 'master/Binaries/2.0.0-preview1-001950-00/runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform.5.3.0-preview1-001950-00.symbols.nupkg'
2017-04-10T16:21:28.6944190Z [TARGET     <] [FAIL] [00:12:41.229] PublishCoreHostPackages                                    (Microsoft.DotNet.Host.Build.PublishTargets.PublishCoreHostPackages)
2017-04-10T16:21:28.6958380Z [TARGET     <] [FAIL] [00:12:41.229] PublishArtifacts                                           (Microsoft.DotNet.Host.Build.PublishTargets.PublishArtifacts)
2017-04-10T16:21:28.6974950Z [TARGET     <] [FAIL] [00:12:41.229] Publish                                                    (Microsoft.DotNet.Host.Build.PublishTargets.Publish)
2017-04-10T16:21:28.6988030Z [TARGET     <] [FAIL] [00:12:41.230] Default                                                    (Standard Goals)
2017-04-10T16:21:28.7003000Z Build failed: System.AggregateException: One or more errors occurred. (The specified block list is invalid.) ---> Microsoft.WindowsAzure.Storage.StorageException: The specified block list is invalid.
2017-04-10T16:21:28.7016930Z    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
2017-04-10T16:21:28.7030000Z --- End of stack trace from previous location where exception was thrown ---
2017-04-10T16:21:28.7043150Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Which according to @dagood, that error is caused by 2 legs of the build uploading the same blob at the same time (which is happening here).

**Comment by dagood** [comment]
To link them together:
 * This issue tracks a specific case of https://github.com/dotnet/core-setup/issues/1994 (tracking all overlap).
 * Regardless of solution, stopping this exception from blocking builds is https://github.com/dotnet/core-setup/issues/1824.

**Comment by joperezr** [comment]
I've put up a PR to fix this specific issue. To be clear, as @dagood this is only one of the many instances of the problem, since even for netcoreapp, we have the case where the Identity package gets produced by multiple builds, so we might run into the same issue.
