### ISSUE TITLE
ASP.NET MVC fails with "Cannot find compilation library location for package 'Microsoft.Win32.Registry'" on Ubuntu

### ISSUE THREAD

**Issue by mikeharder** [dotnet/core-setup#2113]
## Steps to reproduce
1. VM with clean Ubuntu 16.04
2. Install dotnet-dev-1.0.1 to install dependencies (https://www.microsoft.com/net/core#linuxubuntu)
3. wget https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005817/dotnet-dev-ubuntu-x64.2.0.0-preview1-005817.tar.gz
4. mkdir dotnet-dev-ubuntu-x64.2.0.0-preview1-005817
5. tar xf dotnet-dev-ubuntu-x64.2.0.0-preview1-005817.tar.gz -C dotnet-dev-ubuntu-x64.2.0.0-preview1-005817
6. mkdir mvc
7. cd mvc
8. ../dotnet-dev-ubuntu-x64.2.0.0-preview1-005817/dotnet new mvc
9. ../dotnet-dev-ubuntu-x64.2.0.0-preview1-005817/dotnet run

## Exception
```
Unhandled Exception: System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
```

## grep -r DependencyModel *
 ```
bin/Debug/netcoreapp2.0/mvc.deps.json:          "Microsoft.Extensions.DependencyModel": "2.0.0-preview1-002028",
bin/Debug/netcoreapp2.0/mvc.deps.json:      "Microsoft.Extensions.DependencyModel/2.0.0-preview1-002028": {
bin/Debug/netcoreapp2.0/mvc.deps.json:          "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll": {}
bin/Debug/netcoreapp2.0/mvc.deps.json:          "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll": {}
bin/Debug/netcoreapp2.0/mvc.deps.json:    "Microsoft.Extensions.DependencyModel/2.0.0-preview1-002028": {
obj/project.assets.json:          "Microsoft.Extensions.DependencyModel": "2.0.0-preview1-002028",
obj/project.assets.json:      "Microsoft.Extensions.DependencyModel/2.0.0-preview1-002028": {
obj/project.assets.json:          "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll": {}
obj/project.assets.json:          "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll": {}
obj/project.assets.json:    "Microsoft.Extensions.DependencyModel/2.0.0-preview1-002028": {
obj/project.assets.json:        "lib/net451/Microsoft.Extensions.DependencyModel.dll",
obj/project.assets.json:        "lib/netstandard1.3/Microsoft.Extensions.DependencyModel.dll",
obj/project.assets.json:        "lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll",
obj/project.assets.json:        "build/Microsoft.Extensions.DependencyModel.dll",
obj/project.assets.json:        "build/desktop/Microsoft.Extensions.DependencyModel.dll",
```

https://github.com/dotnet/core-setup/pull/2039 was thought to fix this, but MVC still fails after this change.

**Comment by mikeharder** [comment]
Root cause suspected to be https://github.com/dotnet/sdk/issues/1130.

**Comment by eerhardt** [comment]
Fixing now.

**Comment by eerhardt** [comment]
PR up to fix this:  https://github.com/dotnet/sdk/pull/1134.

Will need to get that merged into dotnet/sdk and then that build merged into dotnet/cli.

**Comment by eerhardt** [comment]
This is fixed by above PR

**Comment by mikeharder** [comment]
Verified fixed in the latest ASP.NET builds.

**Comment by alexvy86** [comment]
@eerhardt / @mikeharder I'm seeing the same error ('Cannot find compilation library location for package <package-name>') with a barebones MVC under Windows, when I reference a DLL file in the web app. Do you think that is addressed by the fix as well? Note that the DLL is just a file, not a NuGet package, and by the error text it sounds like something is trying to treat it as a package. It seems that it happens for an MVC web app (not an Empty one), when targeting netcoreapp2.0 or net461.

**Comment by scout208** [comment]
Hi, I'm receiving this error when I try to deploy to Azure. I'm referencing the stable build .NET Core 2.0 SDK, I think. I had no problems running it locally, but now this error is getting thrown on Azure. I don't know why this is happening or how to fix it. Can anyone help?

**Comment by colindekker** [comment]
Have the same issue as @scout208

**Comment by eerhardt** [comment]
Can you share what your .csproj looks like?

**Comment by colindekker** [comment]
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
  </PropertyGroup>

  <ItemGroup Label="ms-aspnetcore">
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup Label="ms-azure">
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.AzureStorage" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup Label="cloudscribe">
    <PackageReference Include="cloudscribe.Core.Web.Mvc" Version="2.0.32" />
    <PackageReference Include="cloudscribe.Core.Storage.EFCore.MSSQL" Version="2.0.5" />

    <PackageReference Include="cloudscribe.Logging.Web" Version="2.1.1" />
    <PackageReference Include="cloudscribe.Logging.EFCore.MSSQL" Version="2.1.0" />

    <PackageReference Include="cloudscribe.Core.IdentityServerIntegration.Mvc" Version="2.1.0" />
    <PackageReference Include="cloudscribe.Core.IdentityServer.EFCore.MSSQL" Version="2.1.0" />

    <PackageReference Include="cloudscribe.SimpleContactForm" Version="2.0.0" />

    <PackageReference Include="cloudscribe.Kvp.Storage.EFCore.MSSQL" Version="2.0.0" />
    <PackageReference Include="cloudscribe.UserProperties.Kvp" Version="2.0.0" />
    <PackageReference Include="cloudscribe.UserProperties" Version="2.0.0" />

    <PackageReference Include="cloudscribe.Web.Localization" Version="2.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

</Project>

```

**Comment by colindekker** [comment]
I'm trying to see where the rabbithole leads, so been adding the missing assemblies to a copy of what got deployed to Azure one  by one, these are the assemblies missing. These are the assemblies:

- Microsoft.Win32.Registry
- System.Security.Principal.Windows
- System.Data.SqlClient
- System.Runtime.CompilerServices.Unsafe
- System.Security.AccessControl
- System.Security.Cryptography.Cng
- System.Security.Cryptography.Xml
- System.Security.Principal.Windows
- System.Text.Encoding.CodePages

But then the next one is the Microsoft.NETCore.App package itself....

```
D:\1\site\wwwroot>dotnet MyAssembly.dll
Hosting environment: Production
Content root path: D:\1\site\wwwroot
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.NETCore.App'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.LazyMetadataReferenceFeature.get_References()
   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine.GenerateCode(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.<ExecuteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.<InvokeAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.<InvokeCoreAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AspNetCore._Views_Shared__Layout_cshtml.<<ExecuteAsync>b__32_8>d.MoveNext() in D:\d3.tfso.git\D3.Identity\src\Dcubed.Sites.App.ManageIdentity\Views\Shared\_Layout.cshtml:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<SetOutputContentAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Shared__Layout_cshtml.<ExecuteAsync>d__32.MoveNext() in D:\d3.tfso.git\D3.Identity\src\Dcubed.Sites.App.ManageIdentity\Views\Shared\_Layout.cshtml:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at cloudscribe.Core.Web.Middleware.EnforceSiteRulesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SaasKit.Multitenancy.Internal.TenantPipelineMiddleware`1.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SaasKit.Multitenancy.Internal.TenantResolutionMiddleware`1.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

```

**Comment by colindekker** [comment]
PS, the above csproj also does not work without the following. 
PPS: I'm making a copy without any keys or passwords etc. anywhere to link here as a reference. of the project.

`<PreserveCompilationContext>true</PreserveCompilationContext>    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>`

**Comment by colindekker** [comment]
Link to project. For completeness I am on VS2017 15.4.0, preview 6.0

https://weareinspark-my.sharepoint.com/personal/colin_dekker_inspark_nl/_layouts/15/guestaccess.aspx?docid=051166ffb939e4da2bfba72df6f461f96&authkey=AV2Zf_gmfCuOQ_GQPM7gX9E&expiration=2017-10-17T22%3a00%3a00.000Z

**Comment by eerhardt** [comment]
@colindekker - I took the app you provided in your link and published it to an azure app service: http://myassembly20171012100507.azurewebsites.net/.  It seems to be working for me.

The one thing I had to do to the app was commenting out the following lines:

```c#
    public void ConfigureServices(IServiceCollection services)
    {
      //services.ConfigureDataProtectionPersistence();
...

      services.AddIdentityServerConfiguredForCloudscribe()
          .AddCloudscribeCoreEFIdentityServerStorageMSSQL(connectionString)
          .AddCloudscribeIdentityServerIntegrationMvc();
          //.ConfigureIdentityServerSigningCredentials(Configuration, Environment);
```

because I didn't set up and configure those services.  I don't expect those to cause the problems.

To try to debug your issue - can you `dotnet publish` the app locally and run it using `dotnet bin\Debug\netcoreapp2.0\publish\MyAssembly.dll`?  Does that work correctly?

The error you are reporting above is what happens when you don't have any assemblies in the `refs` folder which are needed at runtime.  After you publish, can you ensure the `refs` folder is populated fully?

Another thing to try is to create a new default ASP.NET Core MVC project and publish it to make sure it is working correctly.  If that isn't working, then there are larger issues.

**Comment by scout208** [comment]
I figured out what was causing my problem. @colindekker maybe this will work for yours too. 

In my case, it began with simply a misunderstanding of what was causing the error to be thrown. Turns out I was using the NToastNotify library which uses embedded views. @colindekker are you using any embedded views?

Based on https://github.com/aspnet/Mvc/issues/6021#issuecomment-290745919,

I added `<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>` to my .csproj and it ran just fine.

Here's my new working .csproj,
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="NToastNotify" Version="3.0.2" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>
</Project>
```

**Comment by colindekker** [comment]
Yes, that seems to be the issue! The cloudscribe project has embedded views

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by NicoSymo** [comment]
@scout208 you savd my day!!

I had another trouble which was also saved jst before concerning  the following error 
==> ErrorHandlingMiddleware System.InvalidOperationException: No service for type 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet' has been registered.

here is the solution :
https://developercommunity.visualstudio.com/content/problem/50735/applicationinsights-javascriptsnippet-exception-wi.html

**Comment by hunyhabib** [comment]
I still have same, having .netcore 2.0 with VS2017 Community and added the 2 following fields in the property group : MvcRazorExcludeRefAssembliesFromPublish and MvcRazorCompileOnPublish to false. Trying to deploy with docker on Linux. But Error : Cannot find compilation library location for package 'Microsoft.Win32.Registry' . Is still there.. any help

**Comment by eopeter** [comment]
This issue is fixed in Asp.Net Core 2.1

**Comment by lmcarreiro** [comment]
If I run `dotnet build` on ubuntu, and then `dotnet ./bin/Debug/netcoreapp2.0/MyApp.dll` still on ubuntu, everything works fine.

But if I run `dotnet build` on ubuntu, and then `dotnet <mapped-volume-path>/bin/Debug/netcoreapp2.0/MyApp.dll` inside a docker container (through a mapped volume), I get this Microsoft.Win32.Registry error.

Inside the container it just works when I run `dotnet publish` on ubuntu and then `dotnet <mapped-volume-path>/bin/Debug/netcoreapp2.0/publish/MyApp.dll` inside a docker container.

This is a common scenario for debugging inside a container without having to rebuild the docker image each time the code changes, I wanted to continue debugging running just `dotnet build` instead of `dotnet publish`.

Is it the normal behavior? Why can't I run inside the container the dll built on ubuntu with `dotnet build` instead of `dotnet publish`?

**Comment by eerhardt** [comment]
`dotnet build` and `dotnet run` operations are meant to be "development" time scenarios, and thus, on a single machine.  `dotnet publish` is the operation to allow you to execute an application on a different machine than what it was built on.

Since `dotnet build` expects that it only needs to build for the current machine, it will take some shortcuts. For example, not all dependencies get copied to the `bin` folder.  Instead, dependencies that come from a NuGet package will remain in the NuGet cache, and are loaded from there at runtime. You can see that `dotnet build` is machine-dependent by inspecting the `ApplicationName.runtimeconfig.dev.json` file in your output folder. It will have machine-specific paths inside of it. These paths are used to load dependencies that aren't in the output folder.

It is not supported to build on one machine (outside of the docker container), and then to execute on another machine (inside the docker container).  I can think of 2 ways to fix this:

1. `dotnet publish` outside of the docker container, and then execute inside of the docker container.
2. Use `dotnet run` inside of the docker container.
    a. Note that `dotnet run` will do `dotnet restore`, `dotnet build` under the covers.  So the reason this works is because the `build` happens on the same machine (in the docker container).
