### ISSUE TITLE
Running dotnet new on Gentoo Linux throws NullReferenceException

### ISSUE THREAD

**Issue by GurliGebis** [dotnet/core-setup#2380]
## Steps to reproduce
1: Install Gentoo Linux
2: Download the 2.0.0 preview 1 tar.gz SDK and extract it as explained.
3: Run dotnet new

## Expected  behavior
Download and extraction of the needed packages.

## Actual behavior
The following stacktrace is thrown into the console:

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.NormalizeDistroInfo(DistroInfo distroInfo)
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.LoadDistroInfo()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.GetDistroVersionId()
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted

## Environment data
A clean amd64 Gentoo Linux installation with nothing special installed.

**Comment by GurliGebis** [comment]
This is due to /etc/os-release not having a VERSION_ID tag in Gentoo Linux, since it is built from source, and is using rolling releases.

I will be submitting a PR shortly with a fix.

**Comment by GurliGebis** [comment]
Fix has been merged, closing.
