### ISSUE TITLE
Null point errror on Arch Linux

### ISSUE THREAD

**Issue by BusyJay** [dotnet/core-setup#2405]
## Steps to reproduce
dotnet --version

## Expected  behavior
% dotnet --version
2.0.0-preview2-006071

## Actual behavior
% dotnet --version
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.NormalizeDistroInfo(DistroInfo distroInfo)
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.LoadDistroInfo()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.GetDistroVersionId()
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

-----

I think the problem is dotnet [assumes](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs#L110) that VERSION_ID always exists in /etc/os-release. However archlinux is a rolling-release distribution, so there is no VERSION_ID.

**Comment by omajid** [comment]
Should have been fixed by https://github.com/dotnet/core-setup/pull/2381, I hope.

**Comment by mellinoe** [comment]
Yeah, it looks like the same problem. Please try one of the brand new versions, because #2381 was already merged in.

**Comment by steveharter** [comment]
Closing as assumed fixed
