### ISSUE TITLE
AppBaseCompilationAssemblyResolver throws too early on a published app

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2496]
## Steps to reproduce
While fixing https://github.com/dotnet/sdk/issues/1216 and testing it end-to-end I ran into a problem where `AppBaseCompilationAssemblyResolver` throws an exception too early and doesn't give the other resolvers a chance to resolve the compilation libraries.

This is a problem for this scenario because the assembly we are looking for is in the "runtime store".  However, `AppBaseCompilationAssemblyResolver` is the first resolver in the list and it throws an exception when it can't find the assembly in a "published" app.

So the repro steps are:

1. Take the fix for the above bug at https://github.com/eerhardt/sdk/tree/Fix1216.
2. Using that SDK, `dotnet publish` a blank MVC app that has Razor Pre-Compilation turned off
3. Run the published app

## Expected  behavior
The app should run fine.

## Actual behavior
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Cannot find assembly file Microsoft.AspNetCore.dll at 'F:\DotNetTest\TestWeb\Publish\refs,F:\DotNetTest\TestWeb\Publish\,F:\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25319-02'
System.InvalidOperationException: Cannot find assembly file Microsoft.AspNetCore.dll at 'F:\DotNetTest\TestWeb\Publish\refs,F:\DotNetTest\TestWeb\Publish\,F:\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25319-02'
   at Microsoft.Extensions.DependencyModel.Resolution.AppBaseCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
```

## Environment data
```
>F:\dotnet\dotnet.exe --info
.NET Command Line Tools (2.0.0-preview2-006103)

Product Information:
 Version:            2.0.0-preview2-006103
 Commit SHA-1 hash:  f7ff32a18c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\dotnet\sdk\2.0.0-preview2-006103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d
```

`+` the above SDK fix.

@gkhanna79 @pakrym @ramarag

**Comment by eerhardt** [comment]
I think the fix for this is as simple as removing this chunk of code:

https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.Extensions.DependencyModel/Resolution/AppBaseCompilationAssemblyResolver.cs#L104-L110

and instead just let this return `false` and let the next resolver do its work.

@pakrym said `I was trying to be as restrictive as possible at the time of writing to avoid things being resolved from random locations`, however the assumption that other probing locations isn't valid anymore.

The only other places that will be probed are:

1. The Reference Assemblies folder in Program Files.
1. Using .NET Core 2.0+ host - only the locations the host passes on the AppContext in PROBING_DIRECTORIES, which is the locations the host is probing itself.
1. On Desktop and .NET Core 1.x - it will probe the NUGET_PACKAGES or USERPROFILE\.nuget folders.

If we are concerned about this, we could make a change that only the PROBING_DIRECTORIES are checked for "published apps".  But even the current heuristic of "isPublished" == "does the directory contain a 'refs' folder" doesn't hold anymore, because this folder is removed when MVC Razor pre-compilation is turned on.  So this current check isn't 100% fool-proof either.
