### ISSUE TITLE
If release/1.0.0 or 1.1.0 auto-update makes no upgrades, the upgrade build fails

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#2531]
## Steps to reproduce
Run auto-update in release/1.0.0 (or 1.1.0) when there is no update to be made. This is happening more frequently recently in our auto-upgrade infrastructure.

## Expected  behavior
The build notes that it didn't do any upgrades and ends successfully.

## Actual behavior
The build notes that it didn't do any upgrades, then fails due to an unrelated-looking exception:

```
Build failed: System.Collections.Generic.KeyNotFoundException: No property with key RemoteBranchName was found.
   at Microsoft.DotNet.Cli.Build.Framework.BuildContext.get_Item(String name) in E:\A\_work\84\s\build_projects\Microsoft.DotNet.Cli.Build.Framework\BuildContext.cs:line 35
   at Microsoft.DotNet.Scripts.PushPRTargets.GetRemoteBranchName(BuildTargetContext c) in E:\A\_work\84\s\build_projects\update-dependencies\PushPRTargets.cs:line 123
   at Microsoft.DotNet.Scripts.PushPRTargets.CreatePR(BuildTargetContext c) in E:\A\_work\84\s\build_projects\update-dependencies\PushPRTargets.cs:line 97
   at Microsoft.DotNet.Cli.Build.Framework.BuildContext.ExecTarget(BuildTarget target) in E:\A\_work\84\s\build_projects\Microsoft.DotNet.Cli.Build.Framework\BuildContext.cs:line 144
```

This causes some build mail noise.

**Comment by rakeshsinghranchi** [comment]
@dagood , does this issue fall under build tools ? can you share more context about auto-update, why and how it is used ?

**Comment by dagood** [comment]
No, Core-Setup 1.0.0 and 1.1.0 do not use BuildTools for auto-update. Auto-update produces PRs like these, which update the dependencies Core-Setup uses to build: https://github.com/dotnet/core-setup/pull/2958 https://github.com/dotnet/core-setup/pull/2959.

Here are some docs related to the general auto-update process:
 * https://github.com/dotnet/buildtools/blob/master/Documentation/dependency-auto-update.md (some details not relevant because BuildTools/VersionTools isn't used for Core-Setup 1.0.0/1.1.0)
 * https://github.com/dotnet/versions#build-info

Why do you ask?

**Comment by wtgodbe** [comment]
Closing this since it probably isn't worth fixing before 1.x.x EOL in June
