### ISSUE TITLE
Linux/x64 test fails while building

### ISSUE THREAD

**Issue by seanshpark** [dotnet/core-setup#2617]
I'm building on Ubuntu 16.04, x86-64 and fails with test projects.

I'm new with core-setup and got these failures and not sure it's my environment problem or else. Could anyone give some advice on this?

Skip test
```
./build.sh -skipTests=True
```
is OK.

## Steps to reproduce
```
./build.sh
```

## Expected  behavior
Build with no error

## Actual behavior
```
  [EXEC       >] [....] [00:00:00.000] /home/maxwell/netcore/core-setup/Tools/dotnetcli/dotnet
    build --runtime linux-x64 --framework netcoreapp2.0
    -o /home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/2/StandaloneApp/bin

  [EXEC       <] [FAIL] [00:00:02.828] /home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/2/StandaloneApp>
    /home/maxwell/netcore/core-setup/Tools/dotnetcli/dotnet build
    --runtime linux-x64 --framework netcoreapp2.0
    -o /home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/2/StandaloneApp/bin
    exited with 1

  [EXEC       >] [....] [00:00:02.906] /home/maxwell/netcore/core-setup/Tools/dotnetcli/dotnet
    build --framework netcoreapp2.0
    -o /home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/2/PortableTestApp/bin
  Failed   

Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneApp.GivenThatICareAboutStandaloneAppActivation.Running_Publish_Output_Standalone_EXE_with_Unbound_AppHost_Fails
  Error Message:
   System.TypeInitializationException : The type initializer for 'Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneApp.GivenThatICareAboutStandaloneAppActivation' threw an exception.
  ---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1:
  /home/maxwell/netcore/core-setup/Tools/dotnetcli/dotnet build --runtime linux-x64
  --framework netcoreapp2.0
  -o /home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/2/StandaloneApp/bin
  Standard Output:
  Microsoft (R) Build Engine version 15.2.93.5465
  Copyright (C) Microsoft Corporation. All rights reserved.
  
  /home/maxwell/netcore/core-setup/Tools/dotnetcli/sdk/2.0.0-preview1-005899/Roslyn/Microsoft.CSharp.Core.targets(71,5):
  error MSB6006: "/home/maxwell/netcore/core-setup/Tools/dotnetcli/sdk/2.0.0-preview1-005899/Roslyn/RunCsc.sh" exited with code 1.
  [/home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/2/StandaloneApp/StandaloneApp.csproj]
  
  Build FAILED.
  
  /home/maxwell/netcore/core-setup/Tools/dotnetcli/sdk/2.0.0-preview1-005899/Roslyn/Microsoft.CSharp.Core.targets(71,5):
  error MSB6006: "/home/maxwell/netcore/core-setup/Tools/dotnetcli/sdk/2.0.0-preview1-005899/Roslyn/RunCsc.sh" exited with code 1.
  [/home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/2/StandaloneApp/StandaloneApp.csproj]
      0 Warning(s)
      1 Error(s)
  
  Time Elapsed 00:00:02.48
  
  
  Stack Trace:
     at Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneApp.GivenThatICareAboutStandaloneAppActivation..ctor()
  ----- Inner Stack Trace -----
     at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput)
     at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.BuildProject(DotNetCli dotnet, String runtime, String framework, String outputDirectory)
     at Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneApp.GivenThatICareAboutStandaloneAppActivation..cctor()
  Failed   
Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneApp.GivenThatICareAboutStandaloneAppActivation.Running_Publish_Output_Standalone_EXE_with_Bound_AppHost_Succeeds
  Error Message:
   System.TypeInitializationException : The type initializer for 'Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneApp.GivenThatICareAboutStandaloneAppActivation' threw an exception.
  ---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1:
  /home/maxwell/netcore/core-setup/Tools/dotnetcli/dotnet build --runtime linux-x64
  --framework netcoreapp2.0
  -o /home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/2/StandaloneApp/bin
...
  Total tests: 33. Passed: 0. Failed: 33. Skipped: 0.
...
core-setup/src/test/dir.proj(118,5): error : One or more test runs failed.
    1 Error(s)
```

## Environment data
I'm not sure about this.

**Comment by seanshpark** [comment]
It's my Linux environment problem and found out that
`core-setup/Tools/dotnetcli/sdk/2.0.0-preview1-005899/Roslyn/RunCsc.sh`
script doesn't work properly.
`$( dirname "$SOURCE" )` fail somehow when executed and yet don't know why.
But when I execute this script from the shell, `dirname` line passes.

```bash
#!/usr/bin/env bash
#
# Copyright (c) .NET Foundation and contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
#

set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

"$DIR/../../../dotnet" "$DIR/csc.exe" "$@"
```

**Comment by seanshpark** [comment]
Reason is `/usr/bin` is removed from the `PATH` and `dirname` exist in this folder.
I wonder why and where...

**Comment by seanshpark** [comment]
In `DotNetCli` class of `src/test/TestUtils`, `SanitizeGlobalLocation()` is called for `Exec()` and this `SanitizeGlobalLocation()` removes the folder if `dotnet` program exists in it to `PATH` environment.
I think this is because we want to test the `dotnet` not the installed version.

@ramarag , I've found that code was changed from you. Did you not have any problems with `dirname` command execution? Could you check where that program is and share it to me?
And also `which readlink` too.

**Comment by seanshpark** [comment]
CC gkhanna79

**Comment by seanshpark** [comment]
CC @gkhanna79

**Comment by seanshpark** [comment]
Reason of this is that I have a  setup version of `dotnet` is installed in `/usr/bin` in my workstation.

**Comment by ramarag** [comment]
you can remove it, the scenario it was to help with no longer is viable.
https://github.com/dotnet/core-setup/issues/2611

cc @steveharter

**Comment by seanshpark** [comment]
So, can I remove the line calling `SanitizeGlobalLocation()` ?

I've done a simple build test,
1) core-setup as-is and removed `/usr/bin/dotnet` program
2) core-setup test with not calling `SanitizeGlobalLocation()` in `Exec() and with `/usr/bin/dotnet` 

Both showed same result with having 1 Fail in the output
core-setup/Bin/tests/linux-x64.Debug/dotnetMultilevelSDKLookup/2/cwd> /home/maxwell/netcore/core-setup/Bin/tests/linux-x64.Debug/dotnetMultilevelSDKLookup/2/exe/dotnet help exited with 145

But reported 0 Failed
```
Total tests: 33. Passed: 33. Failed: 0. Skipped: 0.
```

**Comment by seanshpark** [comment]
@ramarag , thank you :), I'll wait for the PR to land.

**Comment by gkhanna79** [comment]
CC @eerhardt

**Comment by steveharter** [comment]
PR #2611 updated to remove SanitizeGlobalLocation.

**Comment by seanshpark** [comment]
@steveharter , build is now ok. thank you :)
