### ISSUE TITLE
VERSION system-wide environment variable causing a test failure

### ISSUE THREAD

**Issue by sstevenkang** [dotnet/core-setup#3593]
I am not sure if this is core-setup repo specific problem or the fact taht VERSION env. variable is a well known env. variable that affects AssemblyVersion property when building dlls. If it is the latter, could you point me to documentation that describes this behavior?

## Steps to reproduce
1. Build a docker image with pre-requisite libraries and tools installed.
2. In the dockerfile add the line `ENV VERSION=2.0.5`
3. Build & run the image
4. Build core-setup repository at v2.0.5 tag via command `./build.sh -release`

## Expected  behavior
5. Build finishes & tests pass

## Actual behavior
5. Test fails:
```
  [xUnit.net 00:00:50.5049171]     Microsoft.DotNet.CoreSetup.Test.HostActivation.LightupApp.GivenThatICareAboutLightupAppActivation.Muxer_activation_of_LightupApp_NoLightupLib_Fails [FAIL]
  [xUnit.net 00:00:50.5061087]       The command error output did not contain expected result: Error:
  [xUnit.net 00:00:50.5061740]         An assembly specified in the application dependencies manifest (LightupLib.deps.json) was not found:
  [xUnit.net 00:00:50.5062100]           package: 'LightupLib', version: '1.0.0'
  [xUnit.net 00:00:50.5062280]           path: 'LightupLib.dll'
  [xUnit.net 00:00:50.5062463]
  [xUnit.net 00:00:50.5062599]       File Name: /build/core-setup/Bin/obj/linux-x64.Release/sharedFrameworkPublish/dotnet
  [xUnit.net 00:00:50.5062773]       Arguments: exec --additional-deps /build/core-setup/Bin/tests/linux-x64.Release/4/LightupLib/bin/LightupLib.deps.json /build/core-setup/Bin/tests/linux-x64.Release/4/LightupClient/bin/LightupClient.dll
  [xUnit.net 00:00:50.5063005]       Exit Code: 140
  [xUnit.net 00:00:50.5063145]       StdOut:
  [xUnit.net 00:00:50.5063274]
  [xUnit.net 00:00:50.5063439]       StdErr:
  [xUnit.net 00:00:50.5063570]       Error:
  [xUnit.net 00:00:50.5063734]         An assembly specified in the application dependencies manifest (LightupLib.deps.json) was not found:
  [xUnit.net 00:00:50.5063897]           package: 'LightupLib', version: '2.0.5'
  [xUnit.net 00:00:50.5064031]           path: 'LightupLib.dll'
  [xUnit.net 00:00:50.5064194]
  [xUnit.net 00:00:50.5064321]
  [xUnit.net 00:00:50.5073545]       Stack Trace:
  [xUnit.net 00:00:50.5084386]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
  [xUnit.net 00:00:50.5084947]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
  [xUnit.net 00:00:50.5085460]         /build/core-setup/src/test/TestUtils/Assertions/CommandResultAssertions.cs(81,0): at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.HaveStdErrContaining(String pattern)
  [xUnit.net 00:00:50.5085936]         /build/core-setup/src/test/HostActivationTests/GivenThatICareAboutLightupAppActivation.cs(75,0): at Microsoft.DotNet.CoreSetup.Test.HostActivation.LightupApp.GivenThatICareAboutLightupAppActivation.Muxer_activation_of_LightupApp_NoLightupLib_Fails()
  Failed   Microsoft.DotNet.CoreSetup.Test.HostActivation.LightupApp.GivenThatICareAboutLightupAppActivation.Muxer_activation_of_LightupApp_NoLightupLib_Fails
  Error Message:
   The command error output did not contain expected result: Error:
    An assembly specified in the application dependencies manifest (LightupLib.deps.json) was not found:
      package: 'LightupLib', version: '1.0.0'
      path: 'LightupLib.dll'

  File Name: /build/core-setup/Bin/obj/linux-x64.Release/sharedFrameworkPublish/dotnet
  Arguments: exec --additional-deps /build/core-setup/Bin/tests/linux-x64.Release/4/LightupLib/bin/LightupLib.deps.json /build/core-setup/Bin/tests/linux-x64.Release/4/LightupClient/bin/LightupClient.dll
  Exit Code: 140
  StdOut:

  StdErr:
  Error:
    An assembly specified in the application dependencies manifest (LightupLib.deps.json) was not found:
      package: 'LightupLib', version: '2.0.5'
      path: 'LightupLib.dll'


  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
     at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
     at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.HaveStdErrContaining(String pattern) in /build/core-setup/src/test/TestUtils/Assertions/CommandResultAssertions.cs:line 81
     at Microsoft.DotNet.CoreSetup.Test.HostActivation.LightupApp.GivenThatICareAboutLightupAppActivation.Muxer_activation_of_LightupApp_NoLightupLib_Fails() in /build/core-setup/src/test/HostActivationTests/GivenThatICareAboutLightupAppActivation.cs:line 75
```
## Environment data
Environment variable `VERSION` is set to `2.0.5`

**Comment by steveharter** [comment]
The test project does not specify a version, so it picks up the VERSION env variable of 2.0.5. A test then assumes the version is 1.0.0 (the default). The test project should be changes to explictely specify version 1.0.0.

**Comment by sstevenkang** [comment]
Thanks for the response.  My question is whether `VERSION` env. variable a special/reserved environment variable.  It seems like an awfully generic name.  Is the env. variable consumed by the cli, or just the build scripts in this repo?

**Comment by steveharter** [comment]
It appears it is a special variable. When set, C# projects built under Visual Studio and `dotnet build` both use it.

cc @weshaggard

**Comment by weshaggard** [comment]
The SDK defaults to reading Version as the AssemblyVersion if it isn't set. See https://github.com/dotnet/sdk/blob/2995c8495082d1dd4bcad35c37007375edf45c6f/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets#L131

**Comment by sstevenkang** [comment]
@weshaggard  thanks for the confirmation!
