### ISSUE TITLE
Custom loaded assembly fail resolving reference to empty package

### ISSUE THREAD

**Issue by per-samuelsson** [dotnet/core-setup#4126]
When loading an assembly using `AssemblyLoadContext.LoadFromAssemblyPath` that reference a package without any assembly, executing code in that assembly fail to resolve the reference. 

Using instead a custom context give me the chance to resolve the load, but what can I return when the package is not containing any assemblies?

## Steps to reproduce
1. Clone repro https://github.com/per-samuelsson/ReproCustomLoadEmptyPackage
2. Follow instructions in README.

## Expected  behavior
At least some way I can get a custom resolver to prevent the exception caused by the fact that no assembly is loaded, when there in fact is no assembly to return. 

## Actual behavior
```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Loader.dll: 'Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.IO.FileNotFoundException : Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

## Environment data
```
dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by per-samuelsson** [comment]
I think I see now what can be done, and realize my custom resolver (not highlighted here) simply is a bit to trivial.

By studying packages part of the dependency tree in the custom loaded app, I noticed that there actually *is* an **assembly** `Microsoft.CodeAnalysis`, just that it hides in package `Microsoft.CodeAnalysis.Common`, not in the **package** `Microsoft.CodeAnalysis`. The right thing for the resolver would obviously be to load it from the former.

There is of course no *requirement* that package names match containing assemblies, just as assembly *file names* don't have to match the actual assembly name.
