### ISSUE TITLE
dotnet command hangs when running "dotnet --version"

### ISSUE THREAD

**Issue by pauldotknopf** [dotnet/core-setup#4484]
## Steps to reproduce

I am on a custom built Linux distribution (x64) using Yocto. I have verified that I have all required dependencies for each .so in the downloaded tarball.

```
#!/usr/bin/env bash
set -e
mkdir /lib64
ln -s /lib/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
mkdir -p /usr/share/dotnet
tar -xzvpf dotnet-sdk-latest-linux-x64.tar.gz -C /usr/share/dotnet
ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

dotnet --version
echo This never get's called.
```

## Expected  behavior

```bash
> dotnet --version
2.1.401
```
## Actual behavior

```bash
> dotnet --version
# never exits, just sits there
```

## Environment data

Some commands work. For example:

```
> dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
> dotnet --list-runtimes
Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> dotnet --list-sdks    
2.1.401 [/usr/share/dotnet/sdk]
```

Both ```dotnet --version``` and ```dotnet --info``` hang indefinitely.

I initially tried the tarballs straight from official download sources when I saw the hang. I thought maybe it have to be because my OS was too different (custom Yocto distribution). So I decided hold out on reporting this issue until I compiled the entire .NET Core SDK using the ```dotnet/source-build``` repo and my custom Yocto cross sysroot. The problem still happened, so I am reporting this issue now.

With my custom built .NET Core SDK (2.1.401, but it happens with official tarballs as well), I set ```COREHOST_TRACE=1``` for you guys to help me figure out what the problem is.

Output of ```dotnet --version``` with ```COREHOST_TRACE=1```: [core-host-trace.log](https://github.com/dotnet/core-setup/files/2297707/core-host-trace.log)

**Comment by pauldotknopf** [comment]
I managed to create a coredump of a simple "Hello World" ```dotnet test.dll```.

```
Thread 3 (LWP 1960):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
No locals.
#1  0x0000003391009a85 in __GI___pthread_mutex_lock (mutex=mutex@entry=0x7fa2ada82a60 <ust_mutex>) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_mutex_lock.c:78
        type = 0
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00007fa2ad82608c in ust_lock () at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-ust-comm.c:142
        sig_all_blocked = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}
        orig_mask = {__val = {18446744067266838271, 0 <repeats 15 times>}}
        ret = <optimized out>
        oldstate = 0
        __func__ = "ust_lock"
#3  0x00007fa2ad827114 in ust_listener_thread (arg=0x7fa2ada7d9e0 <local_apps>) at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-ust-comm.c:1407
        sock_info = 0x7fa2ada7d9e0 <local_apps>
        sock = <optimized out>
        ret = <optimized out>
        prev_connect_failed = 0
        has_waited = <optimized out>
        timeout = <optimized out>
        __func__ = "ust_listener_thread"
        __PRETTY_FUNCTION__ = "ust_listener_thread"
#4  0x0000003391007477 in start_thread (arg=0x7fa2ac7d8700) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_create.c:463
        pd = 0x7fa2ac7d8700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140336655337216, -9029649824060446484, 140733173540734, 140733173540735, 8396800, 140733173540912, 9076272402716256492, -9018705284913469204}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x0000003390cf208f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (LWP 1959):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
No locals.
#1  0x0000003391009af6 in __GI___pthread_mutex_lock (mutex=0x3390a25908 <_rtld_global+2312>) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_mutex_lock.c:113
        id = -1862204628
        type = 1
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x0000003390cc14a3 in __libc_fork () at /usr/src/debug/glibc/2.27-r0/git/sysdeps/nptl/fork.c:65
        pid = <optimized out>
        allp = 0x0
        multiple_threads = true
        runp = <optimized out>
#3  0x0000003391010465 in fork_compat () at /usr/src/debug/glibc/2.27-r0/git/nptl/pt-fork.c:40
No locals.
#4  0x00007fa2ad828196 in get_wait_shm (mmap_size=4096, sock_info=0x7fa2ada7fa20 <global_apps>) at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-ust-comm.c:1139
        wait_shm_fd = <optimized out>
        ret = <optimized out>
        pid = <optimized out>
#5  get_map_shm (sock_info=0x7fa2ada7fa20 <global_apps>) at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-ust-comm.c:1259
        page_size = 4096
        ret = <optimized out>
        wait_shm_mmap = <optimized out>
#6  wait_for_sessiond (sock_info=0x7fa2ada7fa20 <global_apps>) at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-ust-comm.c:1300
No locals.
#7  ust_listener_thread (arg=0x7fa2ada7fa20 <global_apps>) at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-ust-comm.c:1373
        sock_info = 0x7fa2ada7fa20 <global_apps>
        sock = <optimized out>
        ret = <optimized out>
        prev_connect_failed = 1
        has_waited = 0
        timeout = <optimized out>
        __func__ = "ust_listener_thread"
        __PRETTY_FUNCTION__ = "ust_listener_thread"
#8  0x0000003391007477 in start_thread (arg=0x7fa2acfd9700) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_create.c:463
        pd = 0x7fa2acfd9700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140336663729920, -9029649824060446484, 140733173540734, 140733173540735, 8396800, 140733173540912, 9076271298372790508, -9018705284913469204}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x0000003390cf208f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (LWP 1958):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
No locals.
#1  0x0000003391009a85 in __GI___pthread_mutex_lock (mutex=mutex@entry=0x7fa2ada82a60 <ust_mutex>) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_mutex_lock.c:78
        type = 0
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00007fa2ad8264dc in ust_lock_nocheck () at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-ust-comm.c:178
        sig_all_blocked = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}
        orig_mask = {__val = {0, 221476092765, 140336674907328, 18446744073709551506, 140336674944704, 140336674908576, 0, 140733173540784, 18446744069414584319, 221476092914, 221476092624, 140336674908576, 140336674860640, 0, 0, 140336674888160}}
        ret = <optimized out>
        oldstate = 0
        __func__ = "ust_lock_nocheck"
#3  0x00007fa2ad82cbdc in lttng_probe_register (desc=desc@entry=0x7fa2ada81b60 <__probe_desc___lttng_ust_lib>) at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-probes.c:207
        ret = <optimized out>
#4  0x00007fa2ad82cd89 in lttng_probe_register (desc=desc@entry=0x7fa2ada81b60 <__probe_desc___lttng_ust_lib>) at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/liblttng-ust/lttng-probes.c:230
No locals.
#5  0x00007fa2ad81da54 in __lttng_events_init__lttng_ust_lib () at /usr/src/debug/lttng-ust/2_2.10.1-r0/lttng-ust-2.10.1/include/lttng/ust-tracepoint-event.h:1008
        ret = <optimized out>
#6  0x000000339080edca in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7ffefed14d18, env=env@entry=0x7ffefed14d30) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-init.c:72
        j = <optimized out>
        jm = <optimized out>
        addrs = <optimized out>
        init_array = <optimized out>
#7  0x000000339080eed6 in call_init (env=0x7ffefed14d30, argv=0x7ffefed14d18, argc=2, l=<optimized out>) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-init.c:118
No locals.
#8  _dl_init (main_map=main_map@entry=0x62b740, argc=2, argv=0x7ffefed14d18, env=0x7ffefed14d30) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-init.c:119
        preinit_array = <optimized out>
        preinit_array_size = <optimized out>
        i = 1
#9  0x0000003390812eb3 in dl_open_worker (a=a@entry=0x7ffefed12f00) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-open.c:511
        args = 0x7ffefed12f00
        file = <optimized out>
        mode = <optimized out>
        call_map = <optimized out>
        dst = <optimized out>
        new = 0x62b740
        __PRETTY_FUNCTION__ = "dl_open_worker"
        r = <optimized out>
        reloc_mode = <optimized out>
        nmaps = <optimized out>
        l = <optimized out>
        maps = <error reading variable maps (value requires 2282232160 bytes, which is more than max-value-size)>
        relocation_in_progress = <optimized out>
        any_tls = <optimized out>
        first_static_tls = <optimized out>
#10 0x0000003390d2a9ac in __GI__dl_catch_exception (exception=exception@entry=0x7ffefed12ee0, operate=operate@entry=0x3390812b20 <dl_open_worker>, args=args@entry=0x7ffefed12f00) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-error-skeleton.c:196
        errcode = 65535
        c = {exception = 0x7ffefed12ee0, errcode = 0x7ffefed12ddc, env = {{__jmpbuf = {140733173542624, -9029368349117552404, 140733173543328, 140336682780151, 2, 221469888512, 9029084969902106860, -9018707885135140628}, __mask_was_saved = 0, __saved_mask = {__val = {0, 0, 221471930162, 221471906216, 221467692066, 7162256605136972140, 8098988775078916716, 8030590389472683109, 6072345634007314291, 3328827817059765319, 7161402270053379634, 3615882935556786508, 13614, 3346019691232651628, 7301002907579514934, 140336691100080}}}}}
        old = <optimized out>
#11 0x000000339081277a in _dl_open (file=0x7ffefed131a0 "/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.3/libcoreclrtraceptprovider.so", mode=-2147483390, caller_dlopen=0x7fa2ae2045f7, nsid=<optimized out>, argc=2, argv=<optimized out>, env=0x7ffefed14d30) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-open.c:594
        args = {file = 0x7ffefed131a0 "/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.3/libcoreclrtraceptprovider.so", mode = -2147483390, caller_dlopen = 0x7fa2ae2045f7, caller_dl_open = 0x3391400ef6 <dlopen_doit+86>, map = 0x62b740, nsid = 0, argc = 2, argv = 0x7ffefed14d18, env = 0x7ffefed14d30}
        exception = {objname = 0x64656c6961460027 <error: Cannot access memory at address 0x64656c6961460027>, errstring = 0x646e6962206f7420 <error: Cannot access memory at address 0x646e6962206f7420>, message_buffer = 0x0}
        errcode = <optimized out>
        __PRETTY_FUNCTION__ = "_dl_open"
#12 0x0000003391400ef6 in dlopen_doit (a=a@entry=0x7ffefed13130) at /usr/src/debug/glibc/2.27-r0/git/dlfcn/dlopen.c:66
        args = 0x7ffefed13130
#13 0x0000003390d2a9ac in __GI__dl_catch_exception (exception=exception@entry=0x7ffefed130d0, operate=operate@entry=0x3391400ea0 <dlopen_doit>, args=args@entry=0x7ffefed13130) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-error-skeleton.c:196
        errcode = 0
        c = {exception = 0x7ffefed130d0, errcode = 0x7ffefed12fdc, env = {{__jmpbuf = {6426744, -9029649532523812628, 6426752, 81, 140733173543328, 140733173543328, 9029084969834997996, -9018707885135140628}, __mask_was_saved = 0, __saved_mask = {__val = {221467677012, 140733174165928, 1005, 221471844856, 4, 140336691102560, 221467678020, 1005, 221471906216, 140336691102560, 140733173543176, 140733173543172, 221467677310, 9029084969267363840, 221471906216, 221471850176}}}}}
        old = <optimized out>
#14 0x0000003390d2aa1f in __GI__dl_catch_error (objname=objname@entry=0x621080, errstring=errstring@entry=0x621088, mallocedp=mallocedp@entry=0x621078, operate=operate@entry=0x3391400ea0 <dlopen_doit>, args=args@entry=0x7ffefed13130) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-error-skeleton.c:215
        exception = {objname = 0x7fa2add15b48 "\301\017", errstring = 0x7fa2ae5122e0 "", message_buffer = 0x7fa2ae204300 "UH\211\345AWAVAUATSH\201\354h\001"}
        errorcode = -512
#15 0x0000003391401535 in _dlerror_run (operate=operate@entry=0x3391400ea0 <dlopen_doit>, args=args@entry=0x7ffefed13130) at /usr/src/debug/glibc/2.27-r0/git/dlfcn/dlerror.c:162
        result = 0x621070
#16 0x0000003391400f91 in __dlopen (file=<optimized out>, mode=<optimized out>) at /usr/src/debug/glibc/2.27-r0/git/dlfcn/dlopen.c:87
        args = {file = 0x7ffefed131a0 "/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.3/libcoreclrtraceptprovider.so", mode = 258, new = 0x7ffefed131a0, caller = 0x7fa2ae2045f7}
        mode = <optimized out>
        file = <optimized out>
#17 0x00007fa2ae2045f7 in ?? () from /opt/medxchange/2.5/sysroots/corei7-64-poky-linux/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.3/libcoreclr.so
No symbol table info available.
#18 0x000000339080edca in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7ffefed14d18, env=env@entry=0x7ffefed14d30) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-init.c:72
        j = <optimized out>
        jm = <optimized out>
        addrs = <optimized out>
        init_array = <optimized out>
#19 0x000000339080eed6 in call_init (env=0x7ffefed14d30, argv=0x7ffefed14d18, argc=2, l=<optimized out>) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-init.c:118
No locals.
#20 _dl_init (main_map=main_map@entry=0x650010, argc=2, argv=0x7ffefed14d18, env=0x7ffefed14d30) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-init.c:119
        preinit_array = <optimized out>
        preinit_array_size = <optimized out>
        i = 0
#21 0x0000003390812eb3 in dl_open_worker (a=a@entry=0x7ffefed13560) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-open.c:511
        args = 0x7ffefed13560
        file = <optimized out>
        mode = <optimized out>
        call_map = <optimized out>
        dst = <optimized out>
        new = 0x650010
        __PRETTY_FUNCTION__ = "dl_open_worker"
        r = <optimized out>
        reloc_mode = <optimized out>
        nmaps = <optimized out>
        l = <optimized out>
        maps = <error reading variable maps (value requires 2282232160 bytes, which is more than max-value-size)>
        relocation_in_progress = <optimized out>
        any_tls = <optimized out>
        first_static_tls = <optimized out>
#22 0x0000003390d2a9ac in __GI__dl_catch_exception (exception=exception@entry=0x7ffefed13540, operate=operate@entry=0x3390812b20 <dl_open_worker>, args=args@entry=0x7ffefed13560) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-error-skeleton.c:196
        errcode = 32766
        c = {exception = 0x7ffefed13540, errcode = 0x7ffefed1343c, env = {{__jmpbuf = {140733173544256, -9029368349083604756, 6594928, 140336686473366, 2, 221469888512, 9029084969646254316, -9018707885135140628}, __mask_was_saved = 0, __saved_mask = {__val = {53, 7018986666877744431, 7308907267039913330, 8242547523246646642, 4993980114270122863, 65280, 0, 7310012246412718707, 3419469542155314223, 4629771061636907072, 4629771061636907072, 6510615555426900570, 6510615555426900570, 2314885530818453536, 2314885530818453536, 0}}}}}
        old = <optimized out>
#23 0x000000339081277a in _dl_open (file=0x64a170 "/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.3/libcoreclr.so", mode=-2147483647, caller_dlopen=0x7fa2ae58a096 <pal::load_library(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, void**)+22>, nsid=<optimized out>, argc=2, argv=<optimized out>, env=0x7ffefed14d30) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-open.c:594
        args = {file = 0x64a170 "/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.3/libcoreclr.so", mode = -2147483647, caller_dlopen = 0x7fa2ae58a096 <pal::load_library(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, void**)+22>, caller_dl_open = 0x3391400ef6 <dlopen_doit+86>, map = 0x650010, nsid = 0, argc = 2, argv = 0x7ffefed14d18, env = 0x7ffefed14d30}
        exception = {objname = 0x0, errstring = 0x0, message_buffer = 0x0}
        errcode = <optimized out>
        __PRETTY_FUNCTION__ = "_dl_open"
#24 0x0000003391400ef6 in dlopen_doit (a=a@entry=0x7ffefed13790) at /usr/src/debug/glibc/2.27-r0/git/dlfcn/dlopen.c:66
        args = 0x7ffefed13790
#25 0x0000003390d2a9ac in __GI__dl_catch_exception (exception=exception@entry=0x7ffefed13730, operate=operate@entry=0x3391400ea0 <dlopen_doit>, args=args@entry=0x7ffefed13790) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-error-skeleton.c:196
        errcode = 0
        c = {exception = 0x7ffefed13730, errcode = 0x7ffefed1363c, env = {{__jmpbuf = {6426744, -9029649532523812628, 6426752, 140733173545920, 6507808, 140733173544952, 9029084969579145452, -9018707885135140628}, __mask_was_saved = 0, __saved_mask = {__val = {0, 0, 221472322653, 18446744073709551504, 221475694208, 3432, 140733173544936, 53, 0, 140733173544952, 0, 6594928, 221535926831, 13, 13, 9}}}}}
        old = <optimized out>
#26 0x0000003390d2aa1f in __GI__dl_catch_error (objname=objname@entry=0x621080, errstring=errstring@entry=0x621088, mallocedp=mallocedp@entry=0x621078, operate=operate@entry=0x3391400ea0 <dlopen_doit>, args=args@entry=0x7ffefed13790) at /usr/src/debug/glibc/2.27-r0/git/elf/dl-error-skeleton.c:215
        exception = {objname = 0x42 <error: Cannot access memory at address 0x42>, errstring = 0x35 <error: Cannot access memory at address 0x35>, message_buffer = 0x7ffefed13bc0 ""}
        errorcode = -512
#27 0x0000003391401535 in _dlerror_run (operate=operate@entry=0x3391400ea0 <dlopen_doit>, args=args@entry=0x7ffefed13790) at /usr/src/debug/glibc/2.27-r0/git/dlfcn/dlerror.c:162
        result = 0x621070
#28 0x0000003391400f91 in __dlopen (file=<optimized out>, mode=<optimized out>) at /usr/src/debug/glibc/2.27-r0/git/dlfcn/dlopen.c:87
        args = {file = 0x64a170 "/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.3/libcoreclr.so", mode = 1, new = 0x7ffefed137e8, caller = 0x7fa2ae58a096 <pal::load_library(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, void**)+22>}
        mode = <optimized out>
        file = <optimized out>
#29 0x00007fa2ae58a096 in pal::load_library (path=0x7ffefed137e8, dll=0x7fa2ae79e778 <g_coreclr>) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/common/pal.unix.cpp:71
No locals.
#30 0x00007fa2ae57b7e9 in coreclr::bind (libcoreclr_path=...) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/cli/coreclr.cpp:47
No locals.
#31 0x00007fa2ae575b36 in run (args=..., out_host_command_result=0x0) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/cli/hostpolicy.cpp:214
No locals.
#32 0x00007fa2ae576ddb in corehost_main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/cli/hostpolicy.cpp:386
No locals.
#33 0x00007fa2ae7c11d9 in execute_app (impl_dll_dir=..., init=0x7ffefed13f90, argc=2, argv=0x7ffefed14d18) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/cli/fxr/hostfxr.cpp:115
No locals.
#34 0x00007fa2ae7cadb2 in fx_muxer_t::read_config_and_execute (host_command=..., host_info=..., app_candidate=..., opts=..., new_argc=<optimized out>, new_argv=<optimized out>, mode=<optimized out>, out_buffer=<optimized out>, buffer_size=<optimized out>, required_buffer_size=<optimized out>) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/cli/fxr/fx_muxer.cpp:1251
No locals.
#35 0x00007fa2ae7cc1d9 in fx_muxer_t::handle_exec_host_command (host_command=..., host_info=..., app_candidate=..., opts=..., argc=<optimized out>, argv=<optimized out>, argoff=<optimized out>, mode=<optimized out>, result_buffer=<optimized out>, buffer_size=<optimized out>, required_buffer_size=<optimized out>) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/cli/fxr/fx_muxer.cpp:1393
No locals.
#36 0x00007fa2ae7cb4f5 in fx_muxer_t::execute (host_command=..., argc=<optimized out>, argv=<optimized out>, host_info=..., result_buffer=0x0, buffer_size=<optimized out>, required_buffer_size=<optimized out>) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/cli/fxr/fx_muxer.cpp:1324
No locals.
#37 0x00007fa2ae7c142a in hostfxr_main_startupinfo (argc=128, argv=0x0, host_path=<optimized out>, dotnet_root=<optimized out>, app_path=<optimized out>) at /usr/src/debug/dotnet-source-build/2.1.401-r0/git/src/core-setup/src/corehost/cli/fxr/hostfxr.cpp:170
No locals.
#38 0x0000000000405408 in ?? ()
No symbol table info available.
#39 0x0000003390c21a57 in __libc_start_main (main=0x4055f0, argc=2, argv=0x7ffefed14d18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffefed14d08) at /usr/src/debug/glibc/2.27-r0/git/csu/libc-start.c:308
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -9029649279864182548, 4208112, 140733173550352, 0, 0, 9029084973129623788, -9018708017789835028}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7ffefed14d30, 0x3390a26110}, data = {prev = 0x0, cleanup = 0x0, canceltype = -19837648}}}
        not_first_call = <optimized out>
#40 0x0000000000403619 in _start ()
No symbol table info available.
```

**Comment by pauldotknopf** [comment]
I'm wondering if this is the same issue as #3561?

**Comment by pauldotknopf** [comment]
I stumbled across this in the coreclr build scripts.

https://github.com/dotnet/coreclr/blob/v2.1.3/netci.groovy#L2370

It seems that someone is at least aware of this issue ;)

**Comment by pauldotknopf** [comment]
And another one: https://github.com/dotnet/coreclr/blob/v2.1.3/tests/scripts/arm32_ci_test.sh#L101

;)

I'm going to open another issue in the coreclr repo, since it is obvious that the issue is there.

**Comment by pauldotknopf** [comment]
So, I found out why my libcoreclr didn't have symbols. I am using source-build to build core-setup, and it is getting some precompiled libcoreclr somewhere from NuGet.

Now, on to find out why core-setup in source-build is ignoring the binaries generated from coreclr.

**Comment by jeffschwMSFT** [comment]
@pauldotknopf, did you move the bug to coreclr?  Can you add a link?

**Comment by pauldotknopf** [comment]
The issue is here: https://github.com/dotnet/coreclr/issues/15693

However, it has been closed. There has still been discussions on it, but I don't think it is on Microsoft's radar. I'm wondering if I should open a new issue, without the noise.

**Comment by jeffschwMSFT** [comment]
CoreCLR is the right repro so I am going to close this issue for now.  Often times it works better to open a new issue and refer to the old closed issue, that way if they are different it will get traction.
