### ISSUE TITLE
Failing Windows x64/x86 HostActivation tests, CompatibilityCheck_Frameworks

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6728]
This test failure or something like it seems to happen on either the win-x64 or win-x86 leg, sometimes both. 10 builds have failed since https://dev.azure.com/dnceng/internal/_build/results?buildId=215733, I didn't check all of them for this, but a few, since it's so hard to get to the actual test failure text.

@vitek-karas @elinor-fung 

Example https://dev.azure.com/dnceng/internal/_build/results?buildId=215901:

Looks like there's still interwoven text:

```
Pattern: ".*The specified framework 'Microsoft.NETCore.App', version '1.1.0', apply_patches=[0-1], version_compatibility_range=[^ ]* is incompatible with the previously loaded version '2.2.0'.*""
...
Launch host: F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\nativehost.exe, app: F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\App.dll, argc: 0, arTgs:h 
e specified framework 'Microsoft.NETCore.App', version '1.1.0', apply_patches=1, version_compatibility_range=minor is incompatible with the previously loaded version '2.2.0'.
```

```
  Failed   Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.HostContext.CompatibilityCheck_Frameworks(scenario: "mixed", frameworkName: "Microsoft.NETCore.App", version: "1.1.0", rollForward: "LatestMinor", isCompatibleVersion: False)
  Error Message:
   Matching the command error output failed. Pattern: ".*The specified framework 'Microsoft.NETCore.App', version '1.1.0', apply_patches=[0-1], version_compatibility_range=[^ ]* is incompatible with the previously loaded version '2.2.0'.*""
File Name: F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\nativehost.exe
Arguments: host_context mixed none F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\mockRuntime\host\fxr\3.0.0-preview7-27807-02\hostfxr.dll F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\App.dll F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\frameworkCompat.runtimeconfig.json
Exit Code: 1
StdOut:
[SECONDARY] hostfxr_initialize_for_runtime_config failed: 0x800080a5

mock coreclr_initialize() called
mock exePath:F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\nativehost.exe
mock appDomainFriendlyName:clrhost
mock propertyCount:10
mock propertyKeys:03911BD8
mock propertyValues:03911C88
mock hostHandle:0573FD18
mock domainId:0573FD0C
mock property[FX_DEPS_FILE] = F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\mockRuntime\shared\Microsoft.NETCore.App\2.2.0\Microsoft.NETCore.App.deps.json
mock property[TRUSTED_PLATFORM_ASSEMBLIES] = F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\App.dll;F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\App_MultiProperty.dll;F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\mockRuntime\shared\Microsoft.NETCore.App\2.2.0\System.Private.CoreLib.dll
mock property[NATIVE_DLL_SEARCH_DIRECTORIES] = F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\;F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\mockRuntime\shared\Microsoft.NETCore.App\2.2.0\;
mock property[PLATFORM_RESOURCE_ROOTS] = F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\;
mock property[FX_PRODUCT_VERSION] = 2.2.0
mock property[AppDomainCompatSwitch] = UseLatestBehaviorWhenTFMNotSpecified
mock property[APP_CONTEXT_BASE_DIRECTORY] = F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\
mock property[APP_CONTEXT_DEPS_FILES] = F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\App.deps.json;F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\mockRuntime\shared\Microsoft.NETCore.App\2.2.0\Microsoft.NETCore.App.deps.json
mock property[PROBING_DIRECTORIES] = 
mock property[APP_TEST_PROPERTY] = VALUE_FROM_APP
mock coreclr_execute_assembly() called
mock hostHandle:DEADBEEF
mock domainId:3435973836
mock argc:0
mock argv:00000000
mock managedAssemblyPath:F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\App.dll
mock coreclr_shutdown_2() called
mock hostHandle:DEADBEEF
mock domainId:3435973836

StdErr:
Tracing enabled @ Fri Jun  7 09:07:58 2019 GMT
--- Invoked hostfxr_initialize_for_dotnet_command_line [commit hash: d732222381cf588fbc06bf6bfe2ae5fc7c5d4808]
Dependency manifest F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\mockRuntime\shared\Microsoft.NETCore.App\2.2.0\Microsoft.NETCore.App.deps.json does not contain an entry for runtime.win-x86.Microsoft.NETCore.DotNetHostPolicy
Loaded library from F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\mockRuntime\shared\Microsoft.NETCore.App\2.2.0\hostpolicy.dll
Tracing enabled @ Fri Jun  7 09:07:58 2019 GMT
--- Invoked hostpolicy [commit hash: d732222381cf588fbc06bf6bfe2ae5fc7c5d4808] [runtime.win-x86.Microsoft.NETCore.DotNetHostPolicy,3.0.0-preview7-27807-02,runtimes/win-x86/native][x86] corehost_initialize = {
}
Deps file: 
Adding native asset runtimes/win-x86/native/coreclr.dll assemblyVersion= fileVersion= from Microsoft.NETCore.App/2.2.0
Adding native asset runtimes/win-x86/native/hostpolicy.dll assemblyVersion= fileVersion= from runtime.win-x86.Microsoft.NETCore.DotNetHostPolicy/2.2.0
Reconciling library Microsoft.NETCore.App/2.2.0
Parsed native deps entry 0 for asset name: coreclr from project: Microsoft.NETCore.App, library version: 2.2.0, relpath: runtimes/win-x86/native/coreclr.dll, assemblyVersion , fileVersion 
Reconciling library runtime.win-x86.Microsoft.NETCore.DotNetHostPolicy/2.2.0
Parsed native deps entry 1 for asset name: hostpolicy from package: runtime.win-x86.Microsoft.NETCore.DotNetHostPolicy, library version: 2.2.0, relpath: runtimes/win-x86/native/hostpolicy.dll, assemblyVersion , fileVersion 
Could not resolve CLRJit path
Initialized context for app: F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\App.dll
--- Invoked hostfxr_run_app [commit hash: d732222381cf588fbc06bf6bfe2ae5fc7c5d4808]
--- Invoked hostfxr_initialize_for_runtime_config [commit hash: d732222381cf588fbc06bf6bfe2ae5fc7c5d4808]
Loaded library from F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\mockRuntime\shared\Microsoft.NETCore.App\2.2.0\coreclr.dll
Launch host: F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\nativehost.exe, app: F:\workspace\_work\1\s\bin\tests\win-x86.Debug\nativeHosting\0\app\App.dll, argc: 0, arTgs:h 
e specified framework 'Microsoft.NETCore.App', version '1.1.0', apply_patches=1, version_compatibility_range=minor is incompatible with the previously loaded version '2.2.0'.
Execute managed assembly exit code: 0x0
--- Invoked hostfxr_close [commit hash: d732222381cf588fbc06bf6bfe2ae5fc7c5d4808]

"
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 32
     at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
     at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.HaveStdErrMatching(String pattern, RegexOptions options) in F:\workspace\_work\1\s\src\test\TestUtils\Assertions\CommandResultAssertions.cs:line 101
     at Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.HostContext.CompatibilityCheck_Frameworks(String scenario, String frameworkName, String version, String rollForward, Nullable`1 isCompatibleVersion) in F:\workspace\_work\1\s\src\test\HostActivationTests\NativeHosting\HostContext.cs:line 427
```

**Comment by vitek-karas** [comment]
This is basically #6711 . The test is multi-threaded (by design) and invokes two entry points in the hosting layer simultaneously (`run_app` and `hostfxr_intialize_for_runtime_config`). The two interleaved messages are coming from different threads and different components. The `Launch host...` comes from `hostpolicy` while the `The specified framework...` comes from `hostfxr`.

Inside one component we do synchronize tracing across all threads, but we currently don't have a mechanism to synchronize tracing across components. Which is exactly what #6711 is about.

**Comment by vitek-karas** [comment]
As a workaround we could redirect tracing to a file instead and rely on reading `stderr` to get the error message which we're looking for in this case. Just be aware that the trace file will still have interleaved text in it, so we should not look into it for anything really.

**Comment by dagood** [comment]
Builds are going through, thanks for the band-aid!
