### ISSUE TITLE
InvalidCastException and ArgumentException in Microsoft.Extensions.DependencyModel Preview 7

### ISSUE THREAD

**Issue by albahari** [dotnet/core-setup#7412]
I've just received two different bug reports from LINQPad 6 users since upgrading Microsoft.Extensions.DependencyModel from Preview 4 to Preview 7 yesterday.

The exceptions are thrown when calling DependencyContextJsonReader.Read(Stream stream).

I can't give you the .deps.json files that caused the exceptions because the users in question haven't included their contact details, however, I can provide the full stack trace for each. I believe it's unlikely that the .deps.json files are corrupt, but can't rule this out. These files will almost certainly have been generated by Visual Studio / MSBuild.

For now, I'm reverting to preview4 of Microsoft.Extensions.DependencyModel so that users can continue to reference .NET Core assemblies reliably in LINQPad 6. However, if you're unable to determine the cause I can consider returning to preview 7 and waiting for a user to report more information.

First, the InvalidCastException:

```
InvalidCastException - Unable to cast object of type 'System.Int32' to type 'System.Int64'.
Source=Microsoft.Extensions.DependencyModel

   at Microsoft.Extensions.DependencyModel.UnifiedJsonReader.CreateUnexpectedException(Utf8JsonReader& reader, String expected)
   at Microsoft.Extensions.DependencyModel.UnifiedJsonReader.ReadStringArray()
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadCompilationOptions(UnifiedJsonReader& reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadCore(UnifiedJsonReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Utf8JsonReader jsonReader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
```

Second, the ArgumentException:

```
ArgumentException - version
Source=Microsoft.Extensions.DependencyModel

   at Microsoft.Extensions.DependencyModel.Dependency..ctor(String name, String version)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadTargetLibraryDependencies(UnifiedJsonReader& reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadTargetLibrary(UnifiedJsonReader& reader, String targetLibraryName)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadTarget(UnifiedJsonReader& reader, String targetName)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadTargets(UnifiedJsonReader& reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadCore(UnifiedJsonReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Utf8JsonReader jsonReader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
```

**Comment by vitek-karas** [comment]
Thanks for reporting these.
The biggest change is that we've switched from `Newtonsoft.Json` to `System.Text.Json` as the underlying JSON parser. There might be some behavioral differences between the two, but I would expect those to be in error cases mostly.

`InvalidCastException`:
This is a bug. The input was invalid (probably a non-array value for the `compilationOptions/defines` property). It should throw `FormatException` but it fails to create the exception message due to some reflection mismatch. I have #7510 to fix this.

`ArgumentException - version`:
I don't know about this one. As far as I can tell the code in this area has the same behavior before/after the change. The exception is thrown when the version is either null or empty string. I tried both cases with P6 and P7 and they behave the same.
For this one it would be really helpful to get the `.deps.json` in question.

In both cases it looks like the `.deps.json` files are invalid - so probably not generated by the build system directly, but without having the exact repro data it's hard to tell for sure.

**Comment by albahari** [comment]
Thanks. When Preview8 is released, I'll ensure that LINQPad includes the .deps.json file in the error report should this happen again.

**Comment by vitek-karas** [comment]
@albahari Unfortunately the fix will not make it into Preview8. P8 is almost done (basically waiting for official build). Once the #7527 gets merged, it should hopefully make P9.

**Comment by vitek-karas** [comment]
#7527 has been merged into the P9 branch.
