### ISSUE TITLE
Failure in Custom Publishing step in .Net Core 3 Internal Servicing Blob Publishing

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/core-setup#8522]
## Steps to reproduce

Re-run the this build+SHA: https://dnceng.visualstudio.com/internal/_build/results?buildId=384514&view=results

## Expected  behavior

Custom Publish job in `.Net Core 3 Internal Servicing` publish blobs.

## Actual behavior

Exception is thrown with the following info:

```
D:\a\1\s\publish\publish-blobs.proj(35,5): error : Error while copying content to a stream.
D:\a\1\s\publish\publish-blobs.proj(35,5): error :    at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
D:\a\1\s\publish\publish-blobs.proj(35,5): error :    at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
D:\a\1\s\publish\publish-blobs.proj(35,5): error :    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
D:\a\1\s\publish\publish-blobs.proj(35,5): error :    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
D:\a\1\s\publish\publish-blobs.proj(35,5): error :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
D:\a\1\s\publish\publish-blobs.proj(35,5): error :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
D:\a\1\s\publish\publish-blobs.proj(35,5): error :    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
D:\a\1\s\publish\publish-blobs.proj(35,5): error :    at Microsoft.DotNet.Build.CloudTestTasks.AzureHelper.RequestWithRetry(TaskLoggingHelper loggingHelper, HttpClient client, Func`1 createRequest, Func`2 validationCallback, Int32 retryCount, Int32 retryDelaySeconds) in /_/tools-local/tasks/BuildTools.Publish/CloudTestTasks/AzureHelper.cs:line 239
```

Note that this might have been caused by a random network problem as other builds with unrelated changes to the failing scenario passed. Retry of same SHA didn't pass because some files were already present in the blob storage account and override seems disabled.

@dagood pointed out that the error might have been a consequence of the [build considering this warning](https://github.com/dotnet/core-setup/blob/54dcbe32cfe5db393e1e6cc6a52593e98e96e94a/tools-local/tasks/BuildTools.Publish/CloudTestTasks/AzureHelper.cs#L239) as an error.

Issue found during the servicing exercise.

/cc @markwilkie

**Comment by dagood** [comment]
Closing: We've only seen this once so far. If it's impactful we can reopen and investigate.
